# Generated by Django 4.1.1 on 2022-12-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
